services:
  - type: web
    name: fake-news-java
    env: java
    plan: free
    rootDir: fake-news-java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/fake-news-java-0.0.1-SNAPSHOT.jar